Create codeql-analysis.yml
iterative/cml pull request #1096
Opened 2022-07-13 09:37 UTC by pandyaved98

There are some Critical and High Priority bugs.

2022-07-15 19:03 UTC, dacbd commented
Thank you, there are certainly some improvements that can be made from that scanning report. The proper domain detection for example would be a great PR if you want to take that on as well 😉. 

As far as the command injection, we might be able to do more? but I feel the nature of the tool doesn't include taking unsanitized input from systems, and if a user did put `cml` in particular `cml runner` behind a service/system that took non-predetermined input the onus would be on that system to sanitize the input. Thoughts @0x2b3bfa0 ?

2022-07-15 19:10 UTC, dacbd commented
@pandyaved98 can you update the PR more closely reflect: https://github.com/iterative/terraform-provider-iterative/blob/master/.github/workflows/codeql-analysis.yml

2022-07-15 19:10 UTC, dacbd requested changes
https://github.com/iterative/cml/pull/1096#issuecomment-1185829932

2022-07-16 07:07 UTC, pandyaved98 commented
## Critical 1: Expression Injection
### .github/workflows/checkbot.yml:0
```
name: checkbot
permissions:
  id-token: write
```
We can set the input value of the expression to an intermediate environment variable. And can put a limit on the permissions of any tokens used by a workflow such as the GITHUB_TOKEN.

## Critical 2: Uncontrolled command line
### src/drivers/gitlab.js:213
```
${dockerVolumesTpl} \
        ${single ? '--max-builds 1' : ''}`;

      return spawn(command, { shell: true });

*This command depends on a server-provided value.
```
If possible, use hard-coded string literals to specify the command to run or library to load. Instead of passing the user input directly to the process or library function, examine the user input and then choose among hard-coded string literals.

If the applicable libraries or commands cannot be determined at compile time, then add code to verify that the user input string is safe before using it.

##High 1: Shell command built from environment values
### src/utils.js:17
```
var cp = require("child_process"),
  path = require("path");
function cleanupTemp() {
  let cmd = "rm -rf " + path.join(__dirname, "temp");
  cp.execSync(cmd); // BAD
}

*Can be replaced with:
var cp = require("child_process"),
  path = require("path");
function cleanupTemp() {
  let cmd = "rm",
    args = ["-rf", path.join(__dirname, "temp")];
  cp.execFileSync(cmd, args); // GOOD
}
```
If possible, use hard-coded string literals to specify the shell command to run, and provide the dynamic arguments to the shell command separately to avoid interpretation by the shell.

Alternatively, if the shell command must be constructed dynamically, then add code to ensure that special characters in environment values do not alter the shell command unexpectedly.

2022-07-18 16:52 UTC, 0x2b3bfa0 commented
> _Thoughts @0x2b3bfa0?_

None of these issues seem critical from a security standpoint; i.e. command execution is required beforehand, rendering them futile. 🤷🏼‍♂️ 

Still, it would be nice to escape properly the affected values. 👍🏼

2022-07-22 20:39 UTC, dacbd commented
@pandyaved98 if you are willing to make the requested modifications please do so; if you don't have the time or are unable to, I'll merge this to an intermediate branch to tweak. That way your contribution is not in limbo for too long.

2022-09-06 23:34 UTC, 0x2b3bfa0 commented
🔔 @pandyaved98, feel free to ping us if you need workflow run approvals; I took some days of vacation and missed the last workflow run request. 🙈

2022-10-08 19:33 UTC, dacbd requested changes

2022-10-08 19:33 UTC, dacbd commented on .github/workflows/codeql-analysis.yml
> +      uses: github/codeql-action/analyze@v2
```suggestion
name: CodeQL

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - assets/**
  schedule:
    - cron: '0 0 * * *' # everyday @ 0000 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - uses: github/codeql-action/autobuild@v2
      - uses: github/codeql-action/analyze@v2
```

2022-10-08 19:36 UTC, dacbd approved these changes
enforce style changes

2022-10-08 22:17 UTC, merged