commit --pr=true by default
iterative/cml pull request #1205
Opened 2022-10-04 13:03 UTC by tasdomas

Closes #1139.

2022-10-06 15:10 UTC, tasdomas commented
The more I look at this, the less it's making sense - marking as draft for now.

2022-10-10 14:03 UTC, casperdcl requested changes
was thinking something more like this.

but my tests show it's not quite fully backwards-compatible:

- works: `cml comment create report.md --pr`
- works: `cml comment create --pr --publish report.md`
- works: `cml comment create report.md --pr=auto`
- fails: `cml comment create --pr report.md` (interprets as `--pr=report.md` and complains about no positional arg)

2022-10-10 14:33 UTC, tasdomas commented on bin/cml/comment/create.js
> +    default: true
Should pr number also be a valid choice?

2022-10-13 12:53 UTC, tasdomas commented
Closing, as this is not the solution we're looking for.

2022-10-13 12:53 UTC, closed without merging