Restyled - Exclude yaml files altogether
iterative/cml pull request #1294
Opened 2022-12-20 21:55 UTC by omesser

Should close: https://github.com/iterative/cml/issues/1177

Restyled uses prettier which does weird things to wrapping, it's opinionated
Specifically, here it manifested in weird wrapping of mulitline strings in the github ymls which bothered us - but to be clear, it might be doing similar things in md files or others.

I've taken a look at config options a bit, the only option I see to configure our way around this, is using `--prose-wrap=preserve` for yaml files - which would work 🤷 for this case, but won't protect us from long lines in the general case. An example of passing options to a restyler: https://github.com/iterative/dvc.org/blob/main/.restyled.yaml#L8

Instead I thought it makes more sense to just have restyled not touch yaml files at all - this is what this PR currently does

Also, optionally, I'll go one step further and ask - do we need restyled in this repo at all (+any repo if you ask me, but some disagree)?
it's meant to open PRs with fixes (for less technical contributors) and I'm not sure the CML team needs it (see https://github.com/iterative/terraform-provider-iterative/issues/615)
we have a linting workflow set up, and we can use some better yaml linter if we want (do we?)

@iterative/cml  - you decide

2022-12-20 21:56 UTC, 0x2b3bfa0 commented
@omesser, hasn't @restyled-commits been disabled for this repository a long time ago? 🤔

2022-12-20 21:59 UTC, 0x2b3bfa0 requested changes
This repository hasn's used @restyled-commits in centuries. Did you mean to obliterate the `.restyled.yaml` file and apply your siggested patch on the following line?

https://github.com/iterative/cml/blob/644dfe056e2fd113cd89ee5ead62a6bb92d55bb1/package.json#L45

2022-12-20 22:06 UTC, omesser commented
> This repository hasn's used @restyled-commits in centuries. Did you mean to obliterate the `.restyled.yaml` file and apply your siggested patch on the following line?
> 
> https://github.com/iterative/cml/blob/644dfe056e2fd113cd89ee5ead62a6bb92d55bb1/package.json#L45

Yes, changing the PR @0x2b3bfa0 thanks!
I guess I read [this](https://github.com/iterative/cml/pull/1272/files#r1053475208) wrong.

2022-12-20 22:13 UTC, 0x2b3bfa0 commented
@omesser, maybe we should also delete `.restyled.yaml` completely as per https://github.com/iterative/cml/pull/1294#pullrequestreview-1225194160, because it's not being used. Unless I got something wrong, the Restyled GitHub App isn't even enabled for this repository,

2022-12-21 00:25 UTC, omesser commented
@0x2b3bfa0 it is done
I can add some yaml linting to "replace" the missing functionality, but... not sure it's really missing honestly. lmk preferences

2022-12-21 00:25 UTC, 0x2b3bfa0 approved these changes
:shipit:

2022-12-21 00:28 UTC, 0x2b3bfa0 commented
I don’t know any good solution for [automatically formatting YAML workflow files](https://iterativeai.slack.com/archives/C01900GSB4J/p1663904459493709?thread_ts=1663903751.101289&channel=C01900GSB4J&message_ts=1663904459.493709), so I guess it’s fine to leave it as-is for now.

2022-12-21 00:31 UTC, merged