Publish includes sha hash
iterative/cml pull request #1304
Opened 2023-01-03 23:51 UTC by dacbd

2023-01-04 08:52 UTC, 0x2b3bfa0 approved these changes
Looks good to me, but it's still pending resolution of https://github.com/iterative/studio/pull/4808#discussion_r1061251480 to determine whether to use the fragment or the query to store commit hashes.

2023-01-06 18:00 UTC, casperdcl reviewed
erm... don't we need to update `genWatermark` (https://github.com/iterative/cml/blob/506e4e8d60e48e2ee4e99cfe9ff38ad6ec6a8f7f/src/cml.js#L206) instead?

2023-01-10 11:25 UTC, tasdomas requested changes
I don't think this will solve our issue with the studio integration.

We need to augment `WATERMARK_IMAGE` with a query fragment indicating the commit sha in [`genWatermark`](https://github.com/iterative/cml/pull/1304/files#diff-509933ea8efc212e9e460c2b844fcbd03061d80cef264781b632118f971e4584L187), but then the tricky bit is updating the logic we use to determine updatable comments [here](https://github.com/iterative/cml/pull/1304/files#diff-509933ea8efc212e9e460c2b844fcbd03061d80cef264781b632118f971e4584L295) and [here](https://github.com/iterative/cml/pull/1304/files#diff-509933ea8efc212e9e460c2b844fcbd03061d80cef264781b632118f971e4584L310)

2023-01-10 11:25 UTC, tasdomas commented on src/cml.js
> +      uri = addshaUri({ uri, sha });
I don't think this is the correct place to add this. This just adds a query parameter to urls of published resources.

2023-01-11 05:26 UTC, dacbd commented
I tested here to verify the changes work, but feel free to re-test in another way. https://github.com/iterative/cml-playground/pull/286

2023-01-11 14:53 UTC, tasdomas commented on src/cml.js
> +      uri = addshaUri({ uri, sha });
Do we need this as well?

2023-01-12 23:28 UTC, closed without merging