Add the option to define the target branch on pull requests
iterative/cml pull request #1326
Opened 2023-01-23 12:37 UTC by dfinteligenz

Adds the option to select the target branch of the PR to be created.
In case of not setting the `targetBranch` option, the behavior is the same as before, it will take the currently selected branch.

An example where the PR will be created with the `main` branch as the target branch:
`cml pr create . --targetBranch=main`

2023-01-27 11:35 UTC, dfinteligenz commented on src/cml.js
> +          'git',
Fixed!

2023-02-03 08:08 UTC, tasdomas approved these changes

2023-02-07 18:38 UTC, dacbd requested changes
g2g https://github.com/iterative/cml-playground/actions/runs/4116875527/jobs/7107481386

functionally works just fine, I think that there might be an edge case worth documenting.

if you are executing this command from `branchA` targeting `branchB` your command may pick up unintended changes.

example: 
- `branchA` has some misc changes say related to your workflow.
- ci pipeline starts executing and makes additional changes to the repo
- within `branchA` your pipeline executes `cml pr create --target-branch branchB .`

This will pr the changes provided within your pipeline (as expected and standard with other uses) but also all commits up till their shared parent. This may come as a surprise compared to what users might be expecting if they have previous experience with the `cml pr create` cmd.

---

Where x represents your ci run and perhaps other modifications
```
    /-b1-b2-(x)
a1-/
```
using this command with result in:
```
a1-b1-b2-(x)
```
this is distinctly different from what users might be expecting from other usage of `cml pr` expecting something like:
```
a1-(x)
```
or
```
    /-b1-b2-\
a1-/---------\(x)
```

Hopefully, I have explained this well enough? Playing with it I'm not sure of the intended use case and how this is better than the current behavior (controlling the target branch via the context of the command's execution)

you can see a small example this here: https://github.com/iterative/cml-playground/pull/323 where https://github.com/iterative/cml-playground/pull/323/commits/d3158ffa28cb1357da2f089eb89a47e8e7a58d7c contains unrelated changes from the context of the ci run and https://github.com/iterative/cml-playground/pull/323/commits/9bd660b45e929fc60f2b477c1cada6c76ae56509 contains the changes from the ci run, both potentially logicly separate sets of changes are include in the same PR.

@dfinteligenz can you confirm this is the behavior you are targeting?
⚠️ marking this as "Request changes" until the author confirms the above

2023-02-07 19:31 UTC, casperdcl commented
I don't follow your diagrams @dacbd.

Using `main` in lieu of `branchA` (because idk how to change `defaultBranchName` in GH mermaid), I assume you start with:

```mermaid
gitGraph
commit id:"a1"
branch "branchB"
commit id:"b1"
commit id:"b2"
```

If `b2` does `cml pr --rebase` (to create a new commit `ci` with PR target `branchB`) you will have:

```mermaid
gitGraph
commit id:"a1"
branch "branchB"
commit id:"b1"
commit id:"b2"
commit id:"ci"
```

but if `b2` does `cml pr --target-branch=main --rebase` you will have:

```mermaid
gitGraph
commit id:"a1"
commit id:"b1"
commit id:"b2"
commit id:"ci"
```

Are you saying users might be expecting this instead:

```mermaid
gitGraph
commit id:"a1"
branch branchB
commit id:"b1"
commit id:"b2"
checkout main
commit id:"ci"
```

... or something else?

2023-02-07 20:55 UTC, dacbd commented
@casperdcl yes, I feel your last case is what users who have used cml pr in the past would naturally expect. However regardless of any options the they specify (`--rebase`) they will essentially end with the entirety of any changes which already exist in their base branch being included in their PR to the target branch. 

**I want to confirm this is what the Author wants. If this is the case the PR is g2g.** 
However, while I initially agreed this seems like a logical option to have, I feel like this is likely to scoop up additional changes that most users might not intend. It might just be my failure of imagination to picture how this new mode of operation is actually useful, as such I just want to confirm this is the intended behavior the Author wants.

2023-02-13 19:31 UTC, dacbd approved these changes
@dfinteligenz thanks, I will get this merged today. I can't say for certain when we will do another release, but the end of the week or early next week seems reasonable.

2023-02-13 19:34 UTC, merged

2025-05-15 08:38 UTC, Sexton1991 commented on src/cml.js
Let