Improve error message
iterative/cml pull request #1349
Opened 2023-02-11 21:12 UTC by balazspeczeli

Please see diff.

2023-02-11 21:15 UTC, dacbd approved these changes
Simple, please feel free to spot any others.

2023-02-12 00:42 UTC, dacbd requested changes

2023-02-12 00:42 UTC, dacbd commented on src/analytics.js
> +  if (!data) throw new Error('data is not set, can\'t calculate a deterministic uuid');
```suggestion
  if (!data) throw new Error("data is not set, can't calculate a deterministic uuid");
```

2023-02-12 00:45 UTC, dacbd approved these changes

2023-02-13 19:26 UTC, dacbd commented
@balazspeczeli please run `npm run lintfix` and I can merge this.

2023-02-14 09:38 UTC, tasdomas approved these changes

2023-02-14 15:24 UTC, merged