Add support for Organisation registration token
iterative/cml pull request #277
Opened 2020-09-29 11:41 UTC by JamesMowatt

This PR adds support for organisation level runner registration in Github, you are able to register a runner that can be used by multiple repositories.

2020-09-30 07:28 UTC, DavidGOrtega requested changes
Lets remove this if moving this block after the organization check if block

```js
if (/*is organization */) {
//do
}




```

2020-09-30 07:28 UTC, DavidGOrtega commented on src/github.js
> +  if (typeof owner !== 'undefined' && typeof repo !== 'undefined') {
Lets remove this if putting the block below the organization code 

```js
if (typeof owner !== 'undefined' && typeof repo === 'undefined') {
//do
}


```

2020-09-30 07:28 UTC, DavidGOrtega commented on src/github.js
> +  if (typeof owner !== 'undefined' && typeof repo !== 'undefined') {
typeof owner !== 'undefined' does not have to be checked since its a condition of both

2020-09-30 07:29 UTC, DavidGOrtega commented
@JamesMowatt The idea is to pass  ```--RUNNER_REPO="https://github.com/myorg"``` ?

2020-09-30 08:01 UTC, DavidGOrtega commented
Looks great! Just only minor issues @JamesMowatt 

Something missing is Gitlab. Same functionality has to be offered. 
Would be possible for you to do it? If not no worries.

2020-09-30 17:30 UTC, JamesMowatt commented
> @JamesMowatt, thanks for the help! 
> 
> The idea is to pass `--RUNNER_REPO="https://github.com/myorg"` ?

Yes, you would only pass the organisation.



> Looks great! Just only minor issues @JamesMowatt
> 
> Something missing is Gitlab. Same functionality has to be offered.
> Would be possible for you to do it? If not no worries.

I will look to raise the Gitlab work as a separate PR if that is ok?

> Lets remove this if moving this block after the organization check if block
> 
> ```js
> if (/*is organization */) {
> //do
> }
> ```

I have applied these requested changes.

2020-10-01 07:28 UTC, DavidGOrtega commented
Looks perfect!

2020-10-01 07:30 UTC, merged