Add readiness checks
iterative/cml pull request #391
Opened 2021-02-11 15:46 UTC by 0x2b3bfa0

Every driver with self-hosted runner support will create the `/tmp/ready.flag` file once the process is ready to accept new jobs, allowing Kubernetes to detect the ready condition without resorting to arbitrary delays nor trusting the connection to be _quick enough_.

2021-02-11 16:02 UTC, DavidGOrtega commented
👋 @0x2b3bfa0 thanks!
Not sure about the scope of this PR. Could you please elaborate?

2021-02-11 16:05 UTC, DavidGOrtega requested changes

2021-02-11 16:05 UTC, DavidGOrtega commented on bin/cml-runner.js
> +          fs.closeSync(fs.openSync('/tmp/ready.flag', 'w'));
No sync functions. Please use async

2021-02-11 16:05 UTC, DavidGOrtega commented on bin/cml-runner.js
> +          fs.closeSync(fs.openSync('/tmp/ready.flag', 'w'));
No sync functions. Please use async

2021-02-11 16:07 UTC, 0x2b3bfa0 commented
When running the container image from Kubernetes, we should check for readiness before trying to submit the training job to the runner. While a quick readiness test is enough, we risk having a race condition where the job gets submitted while the runner hasn't been registered yet.

https://github.com/vgrengvir/cml_kubernetes_case/pull/1/files

2021-02-11 16:14 UTC, DavidGOrtega commented
Ok, but... who is setting ```ready``` in the log? That log is being constructed by cml class and I dont see anything changing it?

2021-02-11 16:26 UTC, 0x2b3bfa0 commented on bin/cml-runner.js
> +          fs.closeSync(fs.openSync('/tmp/ready.flag', 'w'));
🤦 Sorry.

2021-02-11 16:34 UTC, DavidGOrtega commented
@0x2b3bfa0 we are not sending the job. When re runner is ready the CI will send the job and not before. I think that this might not be needed?

2021-02-11 16:38 UTC, 0x2b3bfa0 commented
@DavidGOrtega: unfortunately, the issue is not about actually _sending_ the job, but _registering_ the runner; see the error [here](https://github.com/vgrengvir/cml_kubernetes_case/actions/runs/557802684) for an example.

2021-02-11 16:44 UTC, DavidGOrtega commented
> Once the first step (launch the runner) completes sucessfully, we need to make sure that the self-hosted runner has been registered prior to unlocking the next job.

We dont need to do such thing, the workflow will wait for a runner. In GH this may lead an. error if the repo did not see a runner with those tags before. If not the case it should work.

2021-02-11 16:55 UTC, 0x2b3bfa0 commented
🤔  After the idle timeout and in the absence of new jobs, runners will unregister themselves as part of the shutdown process:
https://github.com/iterative/cml/blob/c66bdfac5daeaa1deb115a357ff4e8ac3cfea388/bin/cml-runner.js#L97

I understand that in repositories with a low run density, it would be common to have the self-hosted runner list empty in the absence of jobs. I'm not sure about GitLab, but on GitHub this would trigger an error for the next cold-start job.

2021-02-11 17:47 UTC, DavidGOrtega commented
> repositories with a low run density would have the self-hosted runner list empty if there aren't any jobs for a long time. I'm not sure about GitLab, but on GitHub this would (and does) trigger an error for the next cold-start job.

Could you please elaborate? GL nor GH will remove the runner from the list unless you unregister them. They will just be in ```disconnected``` state

2021-02-11 18:25 UTC, 0x2b3bfa0 commented
> _Not GL nor GH will remove the runner from the list unless you unregister them._

Indeed, they don't get automatically unregistered by the platform (_id est_: GitHub or GitLab), but _we are_ explicitly unregistering them on shutdown, through the `cml` code, after surpassing the idle time:

https://github.com/iterative/cml/blob/c66bdfac5daeaa1deb115a357ff4e8ac3cfea388/bin/cml-runner.js#L97
https://github.com/iterative/cml/blob/c66bdfac5daeaa1deb115a357ff4e8ac3cfea388/src/drivers/github.js#L131-L149

I'm able to reproduce all my assertions with [the work repository I created yesterday](https://github.com/vgrengvir/cml_kubernetes_case). 🤷‍♂️

2021-02-11 19:20 UTC, 0x2b3bfa0 commented
**Wrapping up**

- There is a race condition that keeps the actual task from running in a cold start condition. A cold start condition could be either the first time the code is launched on a repository or anytime where all the runners were unregistered and shut down after exceding the [maximum idle time](https://github.com/iterative/cml/blob/c66bdfac5daeaa1deb115a357ff4e8ac3cfea388/bin/cml-runner.js#L277), which defaults to [five minutes](https://github.com/iterative/cml/blob/c66bdfac5daeaa1deb115a357ff4e8ac3cfea388/bin/cml-runner.js#L20).

- Preventing this [race condition](https://en.wikipedia.org/wiki/Race_condition) would imply waiting for the self-hosted runner to be registered before trying to run any self-hosted job; failing to do that would produce an error. This pull request provides a clean and idiomatic way for checking this through a [readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes) when running on Kubernetes.

2021-02-11 20:49 UTC, 0x2b3bfa0 commented
🎉  Built and working as expected from [`0x2b3bfa0/cml`](https://hub.docker.com/repository/docker/0x2b3bfa0/cml).

2021-02-15 16:13 UTC, 0x2b3bfa0 commented
As suggested four days ago, this could be used also in conjunction with the Docker [`HEALTHCHECK`](https://docs.docker.com/engine/reference/builder/#healthcheck) instruction in order to provide a general way of detecting the runner registration on different container-based platforms.

2021-02-16 20:07 UTC, 0x2b3bfa0 commented
Note: I'm still wanting and trying to find a better solution, but this compromise is necessary for the first implementation.

2021-02-26 16:46 UTC, 0x2b3bfa0 commented
Virtually superseded by https://github.com/iterative/terraform-provider-iterative/pull/70

2021-02-26 16:46 UTC, closed without merging