Remove catch-all block for token exceptions
iterative/cml pull request #563
Opened 2021-05-26 22:00 UTC by 0x2b3bfa0

Masking all the errors derived from this function is highly counterproductive in some edge cases. At least, `bad credentials` and `not found` are common but separate errors, and mixing them can lead to long and frustrating blind debugging sessions.

CML components rely heavily on services we don't control, and errors are hard to reproduce and hard to trace. While the happy path should be as pretty as possible for end users, errors should be as verbose as possible and contain as much useful non-sensitive information as we manage to extract.

### See also
* https://github.com/iterative/cml/issues/562#issuecomment-849132532, how this pull request converts a blind debugging nightmare into an immediate solution.
* https://github.com/iterative/cml/pull/554#issuecomment-847922485, extended discussion about the topic.

2021-05-27 12:46 UTC, DavidGOrtega approved these changes
👍

2021-05-27 12:46 UTC, DavidGOrtega commented
We have a couple of this also. One is regarding the GL endpoint @0x2b3bfa0

2021-05-27 15:02 UTC, casperdcl requested changes

2021-05-27 15:02 UTC, casperdcl commented on src/cml.js
> +    await this.runner_token();
- old (wrong): `try { ABC(); } catch { throw "B errored" }`
- current (suboptimal): `ABC();`
- ideal: `try { ABC(); } catch (err) { if (err.msg == "unhelpful msg related to B") throw "B errored (original message: {err})"; else throw err }`

vis e.g. https://github.com/iterative/cml/pull/554#issuecomment-848161657

2021-05-28 22:05 UTC, casperdcl approved these changes

2021-05-28 22:08 UTC, merged