misc YAML workflow tweaks
iterative/cml pull request #668
Opened 2021-07-23 11:59 UTC by casperdcl

- new docker org `dvcorg` -> `iterativeai`
- tidy yaml (unneeded lists, key names)

2021-07-23 16:03 UTC, 0x2b3bfa0 approved these changes

2021-07-24 08:40 UTC, DavidGOrtega requested changes

2021-07-24 08:40 UTC, DavidGOrtega commented on src/drivers/gitlab.js
> +        --docker-image "iterativeai/cml:latest" \
do we have @dmpetrov approval for this? originally it was setup under the umbrella of dvcorg on purpose

2021-07-27 17:44 UTC, casperdcl commented
related: https://hub.docker.com/r/iterativeai/cml/tags isn't updated yet https://hub.docker.com/r/dvcorg/cml/tags is fine.

2021-07-27 18:56 UTC, merged