Default to `HEAD` on `send-comment --commit-sha`
iterative/cml pull request #992
Opened 2022-04-29 13:13 UTC by 0x2b3bfa0

Closes #991

2022-04-29 13:19 UTC, DavidGOrtega requested changes

2022-04-29 13:27 UTC, 0x2b3bfa0 commented on bin/cml/send-comment.js
> +        default: 'HEAD',
Not an issue? See https://github.com/iterative/cml/pull/790#issuecomment-954655519

2022-04-29 13:30 UTC, 0x2b3bfa0 commented on bin/cml/send-comment.js
> +        default: 'HEAD',
Yes, [to my mind] you were absolutely right. Commenting on `triggerSha` after `cml pr` is pointless and [astonishing](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

2022-05-02 08:43 UTC, casperdcl approved these changes

2022-05-02 08:43 UTC, casperdcl commented on bin/cml/send-comment.js
> +        default: 'HEAD',
What about non-PR use cases?

```bash
local$ git commit -m experiment && git push
ci-cd$ dvc repro && git add -am "experiment results" && git push
ci-cd$ cml send-comment # probably ok to change from triggerSha to HEAD
```

2022-05-02 08:49 UTC, 0x2b3bfa0 commented on bin/cml/send-comment.js
> +        default: 'HEAD',
Again, the “expected” behavior, if any, would be commenting on the current commit, not on the triggering one. 🤔 

Even if it's a “breaking” change for some workflows, nobody is going to notice the difference.

2022-05-04 04:48 UTC, merged